=== api-evangelist/amazon-private-ca/json-schema/amazon-private-ca-asn1subject-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-private-ca/refs/heads/main/json-schema/amazon-private-ca-asn1subject-schema.json",
  "title": "ASN1Subject",
  "description": "Contains information about the certificate subject. The <code>Subject</code> field in the certificate identifies the entity that owns or controls the public key in the certificate. The entity can be a user, computer, device, or service. The <code>Subject </code>must contain an X.500 distinguished name (DN). A DN is a sequence of relative distinguished names (RDNs). The RDNs are separated by commas in the certificate.",
  "type": "object",
  "properties": {
    "Country": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CountryCodeString"
        },
        {
          "description": "Two-digit code that specifies the country in which the certificate subject located."
        }
      ]
    },
    "Organization": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String64"
        },
        {
          "description": "Legal name of the organization with which the certificate subject is affiliated. "
        }
      ]
    },
    "OrganizationalUnit": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String64"
        },
        {
          "description": "A subdivision or unit of the organization (such as sales or finance) with which the certificate subject is affiliated."
        }
      ]
    },
    "DistinguishedNameQualifier": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ASN1PrintableString64"
        },
        {
          "description": "Disambiguating information for the certificate subject."
        }
      ]
    },
    "State": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String128"
        },
        {
          "description": "State in which the subject of the certificate is located."
        }
      ]
    },
    "CommonName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String64"
        },
        {
          "description": "<p>For CA and end-entity certificates in a private PKI, the common name (CN) can be any string within the length limit. </p> <p>Note: In publicly trusted certificates, the common name must be a fully qualified domain name (FQDN) associated with the certificate subject.</p>"
        }
      ]
    },
    "SerialNumber": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ASN1PrintableString64"
        },
        {
          "description": "The certificate serial number."
        }
      ]
    },
    "Locality": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String128"
        },
        {
          "description": "The locality (such as a city or town) in which the certificate subject is located."
        }
      ]
    },
    "Title": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String64"
        },
        {
          "description": "A title such as Mr. or Ms., which is pre-pended to the name to refer formally to the certificate subject."
        }
      ]
    },
    "Surname": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String40"
        },
        {
          "description": "Family name. In the US and the UK, for example, the surname of an individual is ordered last. In Asian cultures the surname is typically ordered first."
        }
      ]
    },
    "GivenName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String16"
        },
        {
          "description": "First name."
        }
      ]
    },
    "Initials": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String5"
        },
        {
          "description": "Concatenation that typically contains the first letter of the <b>GivenName</b>, the first letter of the middle name if one exists, and the first letter of the <b>Surname</b>."
        }
      ]
    },
    "Pseudonym": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String128"
        },
        {
          "description": "Typically a shortened version of a longer <b>GivenName</b>. For example, Jonathan is often shortened to John. Elizabeth is often shortened to Beth, Liz, or Eliza."
        }
      ]
    },
    "GenerationQualifier": {
      "allOf": [
        {
          "$ref": "#/components/schemas/String3"
        },
        {
          "description": "Typically a qualifier appended to the name of an individual. Examples include Jr. for junior, Sr. for senior, and III for third."
        }
      ]
    },
    "CustomAttributes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CustomAttributeList"
        },
        {
          "description": "<p/> <p>Contains a sequence of one or more X.500 relative distinguished names (RDNs), each of which consists of an object identifier (OID) and a value. For more information, see NIST\u2019s definition of <a href=\"https://csrc.nist.gov/glossary/term/Object_Identifier\">Object Identifier (OID)</a>.</p> <note> <p>Custom attributes cannot be used in combination with standard attributes.</p> </note>"
        }
      ]
    }
  }
}

=== api-evangelist/amazon-private-ca/examples/amazon-private-ca-asn1subject-example.json
{
  "Country": "example-Country",
  "Organization": "example-Organization",
  "OrganizationalUnit": "example-OrganizationalUnit",
  "DistinguishedNameQualifier": "Example CA",
  "State": "example-State",
  "CommonName": "Example CA",
  "SerialNumber": "01:23:45:67:89:ab:cd:ef",
  "Locality": "example-Locality",
  "Title": "example-Title",
  "Surname": "Example CA",
  "GivenName": "Example CA",
  "Initials": "example-Initials",
  "Pseudonym": "example-Pseudonym",
  "GenerationQualifier": "example-GenerationQualifier",
  "CustomAttributes": "example-CustomAttributes"
}
